provider:
  mockapi:
    endpoint: 'https://613b9035110e000017a456b1.mockapi.io/api/v1/contacts'

publisher:
  mailchimp:
    base_address: 'https://us5.api.mailchimp.com/3.0'
    api_key: ${apikey}
    list_id: ${list_id}